# Generated by Django 3.1.4 on 2021-03-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wether_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('main_description', models.CharField(max_length=500)),
                ('temp', models.IntegerField()),
                ('temp_min', models.IntegerField()),
                ('temp_max', models.IntegerField()),
                ('feels_like', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
            ],
        ),
    ]
