# Generated by Django 3.1.4 on 2021-03-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_api', '0002_remove_wether_data_main_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wether_data',
            new_name='Weather_data',
        ),
    ]
