# Generated by Django 3.1.4 on 2021-03-09 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_api', '0003_auto_20210302_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes_recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_description', models.CharField(max_length=600)),
                ('need_umbrella', models.BooleanField()),
                ('type_of_hat', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
