# Generated by Django 3.2 on 2021-05-09 08:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_api', '0004_clothes_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes_recommendation',
            name='data',
        ),
        migrations.RemoveField(
            model_name='clothes_recommendation',
            name='main_description',
        ),
        migrations.RemoveField(
            model_name='clothes_recommendation',
            name='need_umbrella',
        ),
        migrations.RemoveField(
            model_name='clothes_recommendation',
            name='type_of_hat',
        ),
        migrations.RemoveField(
            model_name='clothes_recommendation',
            name='user',
        ),
        migrations.AddField(
            model_name='clothes_recommendation',
            name='city_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='clothes_recommendation',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='weather_data',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='weather_data',
            name='description',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AddField(
            model_name='weather_data',
            name='main',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AddField(
            model_name='weather_data',
            name='warning',
            field=models.CharField(default='clear', max_length=500),
        ),
        migrations.CreateModel(
            name='User_preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_pref', models.IntegerField()),
                ('wind_pref', models.IntegerField()),
                ('fall_out_pref', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
