# Generated by Django 3.2 on 2021-04-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_api', '0005_auto_20210413_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes_recommendation',
            old_name='data',
            new_name='date',
        ),
    ]
