# Generated by Django 3.2 on 2021-04-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_api', '0006_rename_data_clothes_recommendation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes_recommendation',
            name='user',
        ),
    ]
