# Generated by Django 3.2 on 2021-04-14 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_api', '0007_remove_clothes_recommendation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes_recommendation',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 14)),
        ),
    ]
