# Generated by Django 3.2 on 2021-04-14 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_api', '0008_alter_clothes_recommendation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes_recommendation',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
