# Generated by Django 3.2 on 2021-05-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_api', '0009_alter_weather_data_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather_data',
            name='time',
        ),
    ]
