# Generated by Django 3.2 on 2021-05-09 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_api', '0010_remove_weather_data_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather_data',
            name='time',
            field=models.TimeField(default=datetime.time(14, 23, 19, 447522)),
        ),
    ]
