# Generated by Django 3.2.2 on 2021-05-12 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_api', '0013_auto_20210512_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_preferences',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weather_data',
            name='time',
            field=models.TimeField(default=datetime.time(16, 25, 33, 96335)),
        ),
    ]
