# Generated by Django 3.2.2 on 2021-05-12 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_api', '0014_auto_20210512_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_preferences',
            name='user_id',
            field=models.CharField(default='0', max_length=300),
        ),
        migrations.AlterField(
            model_name='weather_data',
            name='time',
            field=models.TimeField(default=datetime.time(20, 26, 8, 86651)),
        ),
    ]
