# Generated by Django 3.2.2 on 2021-05-27 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_api', '0016_auto_20210527_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_preferences',
            name='last_hum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_preferences',
            name='last_temp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weather_data',
            name='time',
            field=models.TimeField(default=datetime.time(12, 45, 38, 895571)),
        ),
    ]
